### ISSUE TITLE
Memory Error Preventing Downloads

### ISSUE THREAD

**Issue by GloveNinja217** [massiveschlong/onlyfans-content-downloader#8]
Good day,

Apologies if the title is misleading. I don't know what is causing my problems and I'm just going off of the outputs I received. I followed all the instructions provided and encountered an issue partway through downloading the videos for an OF Test Account.

Build Notes:
----------------
Firefox - 107.0
Python - 3.10.8
Pip - 22.3.1
uBlock Origin Extension disabled in Firefox

VS Code Terminal Output:
------------------------------
```
<Media Save Location>\videos\0goklklspw7okym43djkk_source.mp4     
127.0.0.1 - - [21/Nov/2022 12:49:37] "POST /download_content HTTP/1.1" 500 -
Traceback (most recent call last):
  File "<Python File Path>\Python310\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)     
  File "<Python File Path>\Python310\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "<Python File Path>\Python310\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "<Python File Path>\Python310\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "<Python File Path>\Python310\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "<Python File Path>\Python310\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "<Python File Path>\Python310\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "c:\Users\steve\OneDrive\PC Files\Documents\UnRAID\Projects\onlyfans-content-downloader-main\download_content.py", line 43, in download_content
    file = requests.get(v, allow_redirects=True)      
  File "<Python File Path>\Python310\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "<Python File Path>\Python310\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "<Python File Path>\Python310\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "<Python File Path>\Python310\site-packages\requests\sessions.py", line 745, in send
    r.content
  File "<Python File Path>\Python310\site-packages\requests\models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
MemoryError
```

Firefox Console Window Output:
-------------------------------------
```
POST http://127.0.0.1:5000/download_content    CORS Missing Allow Origin

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:5000/download_content. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 500.

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
```

I know this has noting to do with free space as my disk still has 100GB of free space after getting through half of the content.

Any assistance would be appreciated.

**Comment by massiveschlong** [comment]
Hey, thank you for the detailed log info.

I can confirm that the code in the GitHub repository still works. Because I've just tested it.

Have you followed step 3 properly?:
⚠️ NOTE: make sure to disable all addons related to blocking, except for adblockers. Examples of browser addons that mess with the code would be "PrivacyBadger", "http://everywhere/", etc.

This issue I used to have too, disabling certain extensions fixed the problem for me.

Have you tried different browsers too? I recommend download a dedicated browser for downloading content, so that you don't have to enable/disable browser extensions every time.

I tested it in Mozilla FireFox Developer Edition, works fine.
Let me know if this solves the issue for you.

**Comment by GloveNinja217** [comment]
Seems to be pretty inconsistent with my experience. One account will spit errors while another will work flawlessly in the same browser. I will take your advice to try this on a dedicated browser with no extensions to minimize any risk of issue. If I notice a pattern or continuous problem I'll open a new issue but will close this for now.
